### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by davidcalhoun** [cameronhunter/local-ssl-proxy#96]
I'm getting an error when trying to install:

```
nfml-AZG:dev dcalhoun$ npm install -g local-ssl-proxy
module.js:544
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
```

This happens in both of these situations:

1. After running `npm install -g local-ssl-proxy`
1. After cloning the git repo and running `npm install`

**Comment by cameronhunter** [comment]
Please try with the latest version (`v2.0.1`)
